# JARVIS AI - Production Prometheus Configuration
# Enhanced monitoring for GPT-OSS 20B migration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'jarvis-production'
    environment: 'production'

# Rule files
rule_files:
  - "rules/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
          - 'ollama-host:9100'
          - 'docker-host:9100'
    scrape_interval: 15s
    metrics_path: '/metrics'

  # JARVIS Brain API
  - job_name: 'brain-api'
    static_configs:
      - targets: ['brain-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: brain-api:8080

  # TTS Service
  - job_name: 'tts-service'
    static_configs:
      - targets: ['tts-service:5002']
    metrics_path: '/metrics'
    scrape_interval: 15s
    honor_labels: true

  # STT Service  
  - job_name: 'stt-service'
    static_configs:
      - targets: ['stt-service:5003']
    metrics_path: '/metrics'
    scrape_interval: 15s
    honor_labels: true

  # Ollama Host Monitoring
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama-host:11434']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    honor_labels: true

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    honor_labels: true

  # Docker Container Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-host:9323']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx/Traefik Metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # GPU Stats Service
  - job_name: 'gpu-stats'
    static_configs:
      - targets: ['gpu-stats-service:5009']
    metrics_path: '/metrics'
    scrape_interval: 10s
    honor_labels: true

  # Blackbox Exporter (endpoint monitoring)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://jarvis.yourdomain.com/health
          - https://jarvis.yourdomain.com/api/health
          - http://ollama-host:11434/api/tags
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Service Discovery for Kubernetes (if applicable)
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 50GB
    wal-compression: true

# Query configuration
query:
  timeout: 2m
  max_concurrent: 20
  max_samples: 50000000

# Remote write configuration for long-term storage
remote_write:
  - url: "https://prometheus-long-term-storage.yourdomain.com/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      max_shards: 200
      min_shards: 1
      max_backoff: 30s
      min_backoff: 100ms

# Feature flags
feature_flags:
  - enable-feature=memory-snapshot-on-shutdown
  - enable-feature=expand-external-labels
  - enable-feature=new-service-discovery-manager