# 🚨 JARVIS AI 2025 - Configuration Alertmanager
# Gestion des alertes avec notifications multi-canal

global:
  # Configuration SMTP
  smtp_smarthost: '${SMTP_HOST:-smtp.gmail.com:587}'
  smtp_from: '${ALERT_EMAIL_FROM:-jarvis-alerts@yourdomain.com}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

  # Configuration Slack
  slack_api_url: '${SLACK_WEBHOOK_URL}'

# Templates pour les notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routage des alertes
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 12h
  receiver: 'jarvis-team'
  
  routes:
    # Alertes critiques -> Notification immédiate
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    
    # Alertes de services IA
    - match:
        service: brain-api
      receiver: 'ai-services-alerts'
      group_interval: 5m
      
    - match:
        service: tts-service
      receiver: 'ai-services-alerts'
      
    - match:
        service: stt-service
      receiver: 'ai-services-alerts'
    
    # Alertes GPU
    - match:
        service: gpu-stats-service
      receiver: 'gpu-alerts'
      repeat_interval: 2m
    
    # Alertes sécurité
    - match_re:
        alertname: '.*Security.*|.*Violation.*|.*Unauthorized.*'
      receiver: 'security-alerts'
      group_wait: 0s
      repeat_interval: 1m

# Définition des receivers
receivers:
  # Équipe par défaut
  - name: 'jarvis-team'
    email_configs:
      - to: '${TEAM_EMAIL:-admin@yourdomain.com}'
        subject: '🤖 JARVIS Alert: {{ .GroupLabels.alertname }}'
        body: |
          🚨 **JARVIS AI System Alert**
          
          **Service:** {{ .GroupLabels.service }}
          **Severity:** {{ .GroupLabels.severity }}
          **Time:** {{ .GroupLabels.timestamp }}
          
          **Alert Details:**
          {{ range .Alerts }}
          - **{{ .Annotations.summary }}**
            {{ .Annotations.description }}
          {{ end }}
          
          **Dashboard:** http://localhost:3001/d/jarvis-overview
          
          ---
          JARVIS AI Monitoring System
    
    slack_configs:
      - channel: '#jarvis-alerts'
        title: '🤖 JARVIS Alert: {{ .GroupLabels.alertname }}'
        text: |
          🚨 **{{ .GroupLabels.severity | toUpper }}** alert from **{{ .GroupLabels.service }}**
          
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}
          
          <http://localhost:3001|View Dashboard>

  # Alertes critiques
  - name: 'critical-alerts'
    email_configs:
      - to: '${CRITICAL_EMAIL:-admin@yourdomain.com}'
        subject: '🔴 CRITICAL: JARVIS System Alert'
        body: |
          🔴 **CRITICAL JARVIS SYSTEM ALERT**
          
          **Service:** {{ .GroupLabels.service }}
          **Time:** {{ .GroupLabels.timestamp }}
          
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Runbook:** {{ .Annotations.runbook_url }}
          {{ end }}
          
          **Immediate Action Required!**
          Dashboard: http://localhost:3001/d/jarvis-overview
    
    slack_configs:
      - channel: '#jarvis-critical'
        title: '🔴 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          <!channel> 🔴 **CRITICAL ALERT**
          
          **Service:** {{ .GroupLabels.service }}
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}
          
          **Action Required Immediately!**
        send_resolved: true

  # Alertes services IA
  - name: 'ai-services-alerts'
    email_configs:
      - to: '${AI_TEAM_EMAIL:-ai-team@yourdomain.com}'
        subject: '🧠 JARVIS AI Service Alert: {{ .GroupLabels.service }}'
        body: |
          🧠 **JARVIS AI Service Alert**
          
          **Service:** {{ .GroupLabels.service }}
          **Severity:** {{ .GroupLabels.severity }}
          
          {{ range .Alerts }}
          **Issue:** {{ .Annotations.summary }}
          **Details:** {{ .Annotations.description }}
          
          **Metrics:**
          {{ if .Annotations.current_value }}
          - Current Value: {{ .Annotations.current_value }}
          {{ end }}
          {{ if .Annotations.threshold }}
          - Threshold: {{ .Annotations.threshold }}
          {{ end }}
          {{ end }}
          
          **AI Dashboard:** http://localhost:3001/d/jarvis-ai-services
    
    slack_configs:
      - channel: '#jarvis-ai'
        title: '🧠 AI Service Alert: {{ .GroupLabels.service }}'
        text: |
          🧠 **{{ .GroupLabels.service }}** service alert
          
          {{ range .Alerts }}
          • **{{ .Annotations.summary }}**
            {{ .Annotations.description }}
          {{ end }}

  # Alertes GPU
  - name: 'gpu-alerts'
    email_configs:
      - to: '${GPU_TEAM_EMAIL:-gpu-admin@yourdomain.com}'
        subject: '🎮 JARVIS GPU Alert'
        body: |
          🎮 **JARVIS GPU Performance Alert**
          
          {{ range .Alerts }}
          **GPU Issue:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          
          **GPU Metrics:**
          {{ if .Annotations.gpu_utilization }}
          - GPU Utilization: {{ .Annotations.gpu_utilization }}%
          {{ end }}
          {{ if .Annotations.gpu_memory }}
          - GPU Memory: {{ .Annotations.gpu_memory }}
          {{ end }}
          {{ if .Annotations.gpu_temperature }}
          - GPU Temperature: {{ .Annotations.gpu_temperature }}°C
          {{ end }}
          {{ end }}
          
          **GPU Dashboard:** http://localhost:3001/d/jarvis-gpu
    
    slack_configs:
      - channel: '#jarvis-gpu'
        title: '🎮 GPU Alert'
        color: 'warning'

  # Alertes sécurité
  - name: 'security-alerts'
    email_configs:
      - to: '${SECURITY_EMAIL:-security@yourdomain.com}'
        subject: '🔒 JARVIS Security Alert'
        body: |
          🔒 **JARVIS SECURITY ALERT**
          
          **ATTENTION: Potential security incident detected**
          
          {{ range .Alerts }}
          **Security Event:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Source:** {{ .Labels.instance }}
          **Time:** {{ .StartsAt }}
          {{ end }}
          
          **Please investigate immediately!**
          Security Dashboard: http://localhost:3001/d/jarvis-security
    
    slack_configs:
      - channel: '#jarvis-security'
        title: '🔒 Security Alert'
        text: |
          <!channel> 🔒 **SECURITY ALERT**
          
          {{ range .Alerts }}
          • **{{ .Annotations.summary }}**
            Source: {{ .Labels.instance }}
          {{ end }}
          
          **Investigate immediately!**
        color: 'danger'
        send_resolved: true

# Configuration de l'inhibition
inhibit_rules:
  # Si le service est down, inhiber les autres alertes de ce service
  - source_match:
      alertname: 'ServiceDown'
    target_match:
      alertname: 'ServiceHighLatency'
    equal: ['service']
  
  # Si critique, inhiber les warnings
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['service', 'alertname']