# 📝 JARVIS AI 2025 - Configuration Loki
# Centralisation des logs avec performance optimisée

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

# Configuration des limites pour JARVIS
limits_config:
  # Limites de performance
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_global_streams_per_user: 10000
  max_query_length: 12000h
  max_query_parallelism: 32
  max_streams_per_user: 0
  max_line_size: 256000
  
  # Rétention des logs JARVIS
  retention_period: 168h  # 7 jours pour les logs normaux
  
  # Optimisation mémoire
  max_entries_limit_per_query: 50000
  max_cache_freshness_per_query: 10m
  
  # Labels spécifiques JARVIS
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  
  # Streaming
  max_concurrent_tail_requests: 10

# Configuration du stockage
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem

# Configuration des index
chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7 jours

# Configuration frontend pour les requêtes
frontend:
  max_outstanding_per_tenant: 100
  compress_responses: true
  log_queries_longer_than: 5s

frontend_worker:
  match_max_concurrent: true

# Configuration analytics pour JARVIS
analytics:
  reporting_enabled: false